editorial:
    resource: "@EditorialBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path:     /index
    defaults: { _controller: EditorialBundle:Default:index }

portada:
    path:     /portada
    defaults: { _controller: EditorialBundle:Default:portada }

login:
    path:     /login
    defaults: { _controller: EditorialBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: EditorialBundle:Security:loginCheck }
    
logout:
    path:     /logout

resena:
    path:     /resena
    defaults: { _controller: EditorialBundle:Default:resena }

novedades:
    path:     /novedades
    defaults: { _controller: EditorialBundle:Default:novedades }
