<?php

namespace ELE\EditorialBundle\Repository;

/**
 * categoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
