<?php

namespace ELE\EditorialBundle\Repository;

/**
 * coleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class coleccionRepository extends \Doctrine\ORM\EntityRepository
{
}
