<?php

namespace ELE\EditorialBundle\Repository;

/**
 * libroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class libroRepository extends \Doctrine\ORM\EntityRepository
{
}
