<?php

namespace ELE\EditorialBundle\Repository;

/**
 * libro_solicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class libro_solicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
