<?php

namespace ELE\EditorialBundle\Repository;

/**
 * solicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solicitudRepository extends \Doctrine\ORM\EntityRepository
{
}
